# version: '3.8'

services:
  # MCP TypeScript Service
  mcp-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - ADK_SERVICE_URL=http://adk-service:8000
    depends_on:
      - adk-service
    volumes:
      - ./logs:/app/logs
    networks:
      - mcp-network

  # ADK Python Service
  adk-service:
    build:
      context: .
      dockerfile: Dockerfile.adk
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge 