name: Deep Research (reusable)
on:
  workflow_call:
    inputs:
      target-path:
        required: true
        type: string
    secrets:
      DEEPR_PT:
        required: true
      DEEPR_SHA256:
        required: true

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: ${{ inputs.target-path }}
          token: ${{ secrets.DEEPR_PT }}
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mcp-analyzer==0.1.0
        working-directory: ${{ inputs.target-path }}

      - name: Run MCP/ADK Integration Debug
        run: python mcp_debug.py
        env:
          DEEPR_PT: ${{ secrets.DEEPR_PT }}
          DEEPR_SHA256: ${{ secrets.DEEPR_SHA256 }}
          API_KEY: ${{ secrets.API_KEY }}

      - name: Run analysis
        run: |
          mcp-analyzer --output=$PWD/${{ inputs.target-path }}/REPORT.md .
        working-directory: ${{ inputs.target-path }}

      - name: Commit report
        run: |
          cd ${{ inputs.target-path }}
          git config user.name github-actions
          git config user.email actions@github.com
          git add REPORT.md
          git commit -m "Deep research report"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.DEEPR_PT }} 